language: java
jdk:
  - openjdk11
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11

script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker

after_success:
  - bash <(curl -s http://localhost:7000/ci)
